name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: iOS build setup
      run: |
          xcodebuild build-for-testing -scheme qa-automation-ios-testUITests -destination 'platform=iOS Simulator,name=iPhone 12' #-allowProvisioningUpdates
          
    - name: E2E tests on iPhone 11
      run: xcodebuild test-without-building -scheme qa-automation-ios-testUITests -destination 'platform=iOS Simulator,name=iPhone 11'
        
    - name: E2E tests on iPhone 12
      run: xcodebuild test-without-building -scheme qa-automation-ios-testUITests -destination 'platform=iOS Simulator,name=iPhone 12'
      
    - name: E2E tests on iPad Air
      run: xcodebuild test-without-building -scheme qa-automation-ios-testUITests -destination 'platform=iOS Simulator,name=iPad Air (3rd generation)'
      
